### ISSUE TITLE
NCoVUtils is depreciated

### ISSUE THREAD

**Issue by seabbs** [yangclaraliu/COVID19_NPIs_vs_Rt#1]
`{NCoVUtils}` has been depreciated in favour of `covidregionaldata` (on CRAN or at github.com/epiforecasts/covidregionaldata)

https://github.com/yangclaraliu/COVID19_NPIs_vs_Rt/blob/08eb838b3628bc1f876c3a32f1141fdb6fa5e6f5/extract_who.R#L1

**Comment by yangclaraliu** [comment]
552b84b9aab1acfb4213da27a6ce0e4a4ae4cf64
