### ISSUE TITLE
Global variables in script

### ISSUE THREAD

**Issue by seabbs** [yangclaraliu/COVID19_NPIs_vs_Rt#10]
https://github.com/yangclaraliu/COVID19_NPIs_vs_Rt/blob/f71a74575722678dcf4171a2b0daff31c17963a3/2_Clustering.R#L4

Do these come from running the previous numbers and having them in your global environment? A comment on that would be great.

**Comment by yangclaraliu** [comment]
83f434254721bd8ac5264c86a2d0731521e00eca
