### ISSUE TITLE
Out of date runtime file

### ISSUE THREAD

**Issue by seabbs** [yangclaraliu/COVID19_NPIs_vs_Rt#13]
https://github.com/yangclaraliu/COVID19_NPIs_vs_Rt/blob/f71a74575722678dcf4171a2b0daff31c17963a3/NPIvsRt_main.r#L1

Looks like this is the main runtime file but won't work with the current layout?

**Comment by yangclaraliu** [comment]
removed this but doesn't look like this is relevant anymore.
will provide a more detailed README that essentially cover the same thing as this original one wasn't that informative.
