### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by seabbs** [yangclaraliu/COVID19_NPIs_vs_Rt#3]
https://github.com/yangclaraliu/COVID19_NPIs_vs_Rt/blob/f71a74575722678dcf4171a2b0daff31c17963a3/0_LoadData.R#L89

Some of the code is a little hard to parse. This section for example looks like it is printed but there is nothing to explain what it is.

**Comment by yangclaraliu** [comment]
3a56fb105b2eabf01370c4a7ed2f298373f9df27
