### ISSUE TITLE
Imputation

### ISSUE THREAD

**Issue by seabbs** [yangclaraliu/COVID19_NPIs_vs_Rt#5]
https://github.com/yangclaraliu/COVID19_NPIs_vs_Rt/blob/f71a74575722678dcf4171a2b0daff31c17963a3/0_LoadData.R#L169

I think I missed this step in the paper. Is this an interpolation so that current policy value is last observed if missing?

**Comment by yangclaraliu** [comment]
Not quite. This is linear interpolation option from `imputeTS` package, function `na_interpolation` - which means it does 2 things
1. If there's missingness like {NA, NA, NA, NA, 5, 6}, imputed results will be {5, 5, 5, 5, 5, 6}
2. If there's missingness like {4, NA, NA, 7}, imputed results will be {4, 5, 6, 7}

So it was used to fix three things
1. Foward missing {NA, NA, a, b}
2. Backward missing {a, b, NA, NA}
3. Central missing {a, NA, b}

In the 3rd case, there's an unfortunate case when a != b, the imputed value could have decimal - which when we convert back to a factor will lead to NAs. Right now I just round it.

e.g. 
original = {0, NA, NA, NA, 1}
imputed_raw = {0, 0.25, 0.5, 0.75, 1}
imputed_final = {0, 0, 1, 1, 1}

revised manuscript and also -
a31dccee60546becd6a7c08230d98a95d61701d7

**Comment by seabbs** [comment]
Ah makes sense - thanks for clarifying.
