### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by seabbs** [yangclaraliu/COVID19_NPIs_vs_Rt#7]
https://github.com/yangclaraliu/COVID19_NPIs_vs_Rt/blob/f71a74575722678dcf4171a2b0daff31c17963a3/1_Descriptives.R#L2

Minor point. In the previous script used pacman to install packages here uses library which doesn't. Some central list of what packages are needed would likely really help reproducibility as would not depending on the tidyverse and instead calling the packages used.

**Comment by yangclaraliu** [comment]
4e3161f82de142880eb75bd8f744d4dfd874e6f5
